sudo: false

cache:
  directories:
    - $HOME/.composer/cache

language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

script:
  - php bin/phpunit --coverage-clover=clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: martin.aarhof@gmail.com
